### ISSUE TITLE
Missing dep on js_of_ocaml-compiler

### ISSUE THREAD

**Issue by zapashcanon** [aantron/bisect_ppx#253] opened 2019-09-02 21:16 UTC
Hi,

I recently tried to compile a project of mine that is using `bisect_ppx`, when running `dune build @all` I got an error saying that `js_of_ocaml-compiler` was missing.

I think either `bisect_ppx` is missing a dep on `js_of_ocaml-compiler` in opam or it should be possible to compile without `js_of_ocaml-compiler` (I guess it's used to export to HTML only ?).

Cheers,

**Comment by aantron** [comment] 2019-09-03 03:54
It should be possible to compile without `js_of_ocaml-compiler`. However, I can't reproduce this problem. Can you say what steps can be taken, from git checkout or download, to see this? I can only get this error if I run `make usage`, which is a test.

Also, try just `dune build`, not `dune build @all`. The latter will build test cases, but the former will build only Bisect_ppx. However, I can't observe the problem even with `dune build @all`.

**Comment by aantron** [comment] 2019-09-03 12:46
Here is the log of a full Travis build from today: https://travis-ci.org/aantron/bisect_ppx/jobs/580171739. Bisect_ppx built successfully, and js_of_ocaml-compiler was not installed.

**Comment by zapashcanon** [comment] 2019-09-03 16:18
Sorry, the problem is not when building Bisect_ppx but when building my software.

I just did `opam install bisect_ppx` then, in my project `dune build @all`, and that's where I got an error saying `js_of_ocaml-compiler` is missing (of course my project is not using `js_of_ocaml-compiler`.

**Comment by aantron** [comment] 2019-09-03 16:23
Which version of `bisect_ppx` was installed? `opam list --installed bisect_ppx`

**Comment by aantron** [comment] 2019-09-03 16:26
And what is the command printed by Dune before the message about `js_of_ocaml-compiler`? That is, what is the full error message?

**Comment by aantron** [comment] 2019-09-03 16:48
I just tried the Bisect Dune starter repo (https://github.com/aantron/bisect-starter-dune#readme), and wasn't able to reproduce this with `master` and with Bisect_ppx 1.4.1 (the last release).

**Comment by zapashcanon** [comment] 2019-09-03 17:19
It's on [this repo](https://git.zapashcanon.fr/zapashcanon/memo).

`opam switch`: `→  4.07.1   ocaml-base-compiler.4.07.1  4.07.1`
`opam list --installed bisect_ppx`: `bisect_ppx 1.4.1`

```sh
dune build @all
Error: Library js_of_ocaml-compiler not found
 (context: default)
Hint: try: opam install js_of_ocaml-compiler
```

When doing `dune build` it's working fine...

**Comment by aantron** [comment] 2019-09-03 17:23
I'll take a look. In the meantime, can you run `dune` with `--verbose`?

Bisect_ppx 1.4.1 doesn't make any mention of Js_of_ocaml (I just grepped the repo to be extra sure). Bisect_ppx `master` introduced a test that uses Js_of_ocaml, but Bisect_ppx itself does not depend on Js_of_ocaml.

**Comment by aantron** [comment] 2019-09-03 17:32
So far, I removed the `preprocess` stanza from `src/dune`, and uninstalled Bisect_ppx 1.4.1, and I am still getting the message about `js_of_ocaml-compiler`. I'm not sure yet what is causing, but I am fairly sure it's not Bisect. Still looking...

**Comment by aantron** [comment] 2019-09-03 17:42
This patch fixes it:

```diff
diff --git a/test/dune b/test/dune
index 0376eb3..b050fa1 100644
--- a/test/dune
+++ b/test/dune
@@ -1,3 +1,3 @@
-(test
+(executable
   (name test)
   (libraries memo))
```

Another option is to run `dune runtest` for tests instead of `dune build @all`.

It looks like Dune overestimates dependencies with `@all`, perhaps that's a Dune bug. I suggest opening an issue at https://github.com/ocaml/dune.

**Comment by aantron** [comment] 2019-09-03 17:52
I see this issue about it: https://github.com/ocaml/dune/issues/1940. I'm closing this issue in this repo, since I assume it's a duplicate. Please let me know if not :)

**Closed by aantron** 2019-09-03 17:52 UTC

**Comment by aantron** [comment] 2019-09-03 17:57
So this patch also works:

```diff
diff --git a/dune-project b/dune-project
index 7815090..e4e62f7 100644
--- a/dune-project
+++ b/dune-project
@@ -1,2 +1,3 @@
-(lang dune 1.6)
+(lang dune 1.11)
 (name memo)
+(explicit_js_mode)
diff --git a/memo.opam b/memo.opam
index 8a9182c..28ff65b 100644
--- a/memo.opam
+++ b/memo.opam
@@ -12,6 +12,7 @@ maintainer: "Léo Andrès (zapashcanon) <leo@ndrs.fr>"
 dev-repo: "git+https://git.zapashcanon.fr/zapashcanon/memo.git"
 
 depends: [
+  "dune" {>= "1.11.0"}
   "ocaml"
 ]
```

**Comment by zapashcanon** [comment] 2019-09-03 18:46
Indeed, sorry, for some reason I was convinced it was because of `bisect_ppx`... Thanks !
