### ISSUE TITLE
Typechecking issue with GADTs under or-patterns

### ISSUE THREAD

**Issue by mbouaziz** [aantron/bisect_ppx#325] opened 2020-06-17 09:06 UTC
As mentioned in an [OCaml PR](https://github.com/ocaml/ocaml/pull/1655#issuecomment-645249604), this code
```ocaml
type _ t = A : unit t | B : bool t

let f : type a. a t -> int =
  fun x -> match x with A | B -> 0
```
is instrumented as
```ocaml
let f : type a. a t -> int =
  fun x ->
    ___bisect_visit___ 2;
    (match x with
     | A|B as ___bisect_matched_value___ ->
         ((((match ___bisect_matched_value___ with
             | A -> (___bisect_visit___ 0; ())
             | B -> (___bisect_visit___ 1; ())
             | _ -> ()))
          [@ocaml.warning "-4-8-9-11-26-27-28"]);
          0))
```
rejected by the typechecker:
```
File "bin/main.ml", line 4, characters 28-29:
4 |   fun x -> match x with A | B -> 0
                                ^
Error: This pattern matches values of type bool t
       but a pattern was expected which matches values of type unit t
       Type bool is not compatible with type unit 
```

Waiting for it to be fixed in OCaml side, maybe the instrumentation could be changed to avoid using `as`?
```
let ___bisect_matched_value___ = x in
match x with ...
```
I don't know how that'd interact with nested or-patterns though.

**Comment by aantron** [comment] 2020-06-17 12:50
I haven't looked into the details of the bug yet, but I can say the reason Bisect inserts this second match expression with an `as` constraint, and that is that the alternative to `as` is to separate the cases completely, and then Bisect will also know which case was taken. However, that has the two disadvantages that (1) it is a much more invasive rewrite of the user's code, and (2) it can't be done if there is a `with` guard, because that guard will have to be duplicated, which will cause it to be evaluated twice in case the match fails.

There are already some cases where Bisect both has to and can separate the case, namely in `v | exception E`, because such "patterns" cannot be re-matched (the information about whether an exception was caught is lost), and because such patterns cannot have a `with` guard. We could change the set of patterns for which Bisect takes this approach somewhat, by checking for a `with` guard and separating the case if it is absent. However, that won't solve the problem for patterns when a `with` guard is present, so I'm hesitant to do it.

Before doing anything, however, I'd like to ask how much pain this is causing? Could you either tweak your code, or insert a `[@coverage off]`? If this is a vanishing issue, perhaps it can make sense to wait for it to be fixed upstream.

If you'd like to see discussion of why Bisect instruments patterns the way it does, let me know, and I'll dig out some issues and comments that go into some depth on it :)

**Comment by aantron** [comment] 2020-06-17 12:59
Considering your suggestion further, it may be a good way to avoid this conclusively :)

**Comment by aantron** [comment] 2020-06-21 16:14
> ```ocaml
> let ___bisect_matched_value___ = x in
> match x with ...
> ```

This would have to be 

```ocaml
let ___bisect_matched_value___ = x in
match ___bisect_matched_value___ with ...
```

to avoid repeating side effects caused by evaluation of `x`. However, it still doesn't quite work, because `x` might raise exceptions that are intended to be handled in `exception` cases of the `match`.

There may be a solution like

```ocaml
match x with
| exception ___bisect_matched_value___ ->
  (match ___bisect_matched_value with
  ...)
| ___bisect_matched_value___ ->
  (match ___bisect_matched_value with
  ...)
```

I'll consider it more this week.

**Comment by aantron** [comment] 2020-08-06 15:06
@mbouaziz It looks like the PR you linked has been updated and merged. Once that is released in OCaml, will it address this issue? If so, then I propose to close it here, as I still haven't come up with a solution that isn't very awkward, given all the constraints from evaluation order, side effects, exceptions, and pattern guards.

**Comment by mbouaziz** [comment] 2020-08-13 13:49
@aantron Unfortunately it wouldn't solve the issue in general as it would require users to add explicit type annotations where none were required without `bisect_ppx`.

Didn't the solution you suggested work? Even a partial one working in easy cases would be a great improvement.

**Comment by aantron** [comment] 2020-11-03 08:47
I converted Bisect to the instrumentation I suggested above in branch `gadt-325`.

This kind of instrumentation interferes with row type inference (for polymorphic variants), because it binds `___bisect_matched_value___` outside of case patterns to values that may, at that point, have variands from any of the cases. The existing instrumentation (using `as` patterns) binds `___bisect_matched_value___` in each case pattern, which narrows its type to only those variands that appear in that pattern. This difference completely breaks compilation of Markup.ml with coverage, and will break many other projects.

Thinking of a workaround. I may have to scan patterns for polymorphic variants and fall back to `as` instrumentation if they are present. That seems very messy, and there is the potential issue of polymorphic variants appearing under GADTs.

**Closed** 2020-11-03 13:08 UTC
Labels: bug

**Comment by aantron** [comment] 2020-11-03 13:16
The linked commit changes the `match` instrumentation to

```ocaml
match e with
| ___bisect_matched_value___ ->
  match ___bisect_matched_value___ with
  | A | B ->
    begin
      match __bisect_matched_value___ with
      | A -> ___bisect_visit___ 0
      | B -> ___bisect_visit___ 1
      | _ -> ()
    end;
    (* user code *)
```

This avoids attaching `as` to the pattern `A | B`, as is done by the previous instrumentation method:

```ocaml
match e with
| A | B as ___bisect_matched_value___ ->
  begin
    match __bisect_matched_value___ with
    | A -> ___bisect_visit___ 0
    | B -> ___bisect_visit___ 1
    | _ -> ()
  end;
  (* user code *)
```

So, the new method should be less invasive, as it does not construct new patterns at all, so there is less risk of the instrumentation itself triggering anything in the compiler that the user's code does not already trigger.

I added the example provided by @mbouaziz as a test case to Bisect_ppx's new test suite, the creation of which was directly motivated by the desire to solve this issue in a sane fashion:

https://github.com/aantron/bisect_ppx/blob/4de17d796a431ca758d006ae1a4259ee39da9cc9/test/instrument/recent/gadt.t#L4-L28

This new instrumentation interferes with inferred row types in polymorphic variants, so they are instrumented in the old way, using `as` patterns:

```ocaml
match e with
| `A | `B as ___bisect_matched_value___ ->
  begin
    match __bisect_matched_value___ with
    | `A -> ___bisect_visit___ 0
    | `B -> ___bisect_visit___ 1
    | _ -> ()
  end;
  (* user code *)
```

cc @gasche. The contortions Bisect has to go through here may be of interest. There is a test with a very simple in case which cannot be instrumented binding `___bisect_matched_value___` outside `match`. This one can be worked around by not emitting `_ -> ()` in the nested `match` expression, but others cannot.

https://github.com/aantron/bisect_ppx/blob/4de17d796a431ca758d006ae1a4259ee39da9cc9/test/instrument/pattern/row.t#L4-L32

Exception cases and patterns in `try ... with ...` are also instrumented using `as`, because, to my knowledge, there is no good way to bind a name to the exception, without either risking catching all exceptions (when the user would like any exception not matching their patterns to go further up the stack), or else using the runtime to get access to the most recent exception caught, which would require a different function on each runtime.

@mbouaziz, can you test Bisect_ppx `master` on your code now? Is the original issue fixed? If there are any more problems, could you open additional issues?

**Comment by gasche** [comment] 2020-11-03 13:41
Thanks for your work on this! Below are comments in no particular order. (cc also @trefis)

1. In an ideal world, `| p as matched_value` should work. It does not work on GADTs right now because of a known limitation of or-patterns involving GADTs. (In retrospect it may have been a mistake to introduce partial support that lets us do or-patterns on GADTs, but not bind them to a variable.) I hope that we will eventually fix this downside of GADTs, so that the old code would start working again, but this is a complex part of the type-checker that evolves slowly. The enriched typing of `p as x` in the PR you discussed goes in the right direction for variants, but it does not work for GADTs.

2. On the other hand, some left-hand-side of clauses will never be bindable to variables, I believe: `| None | exception None_found -> ...`. So in general you may have to "explode" some or-patterns, duplicating the right-hand-side. If you accept to duplicate sometimes, why not duplicate on every or-pattern to make the problem go away? The reason, as I understand, is that in the `exception p` case you can see that you need to duplicate by looking at the parsetree, but in the `A | B` case you don't know a-priori whether duplication is required without looking at the typedtree (to see if there are GADT equations coming with the constructors). (Maybe one day it will be possible *and convenient* to write `ppx_bisect` as a typedtree transformation, rather than a parsetree transformation. Not right now.) But then, what if you decided to duplicate on *all* or-patterns, even those that do not involve GADTs, would there be a problem?

3. I understand how this interacts badly with polymorphic in general (whose open/closed typing uses heuristics coming from pattern-matching exhaustivity). It looks like you need a heterogeneous approach where `exception ...` always get expanded (with potential duplication of right-hand-sides), potential-GADTs have their scrutinee named and then re-matched, and polymorphic variants need to be carefully left in-place. Ugh.

4. Do we really care about which sides of a toplevel or-pattern where taken, and which were not? If you gave up on this fine-grained information, you could have a much simpler implementation. Do you try to keep track of deep or-patterns? (Eg. `Some (A | B)`)? (The transformations you are doing would be very difficult to perform in-depth, but then those are typed in a less complex way, they cannot contain `exception` patterns, etc., so maybe naming the or-pattern always works.)

5. Maybe an approach to solve some of these problems would be to let extension processors give hints to the type-checker: do not try to pressure variants here, etc. I'm open to discussing such things, but in this design space I think that "figuring out how to work from the typedtree directly" is more promising and not necessarily that much more work.

**Comment by aantron** [comment] 2020-11-03 16:47
> 2\. On the other hand, some left-hand-side of clauses will never be bindable to variables, I believe: `| None | exception None_found -> ...`. So in general you may have to "explode" some or-patterns,

Indeed, the instrumenter partitions each pattern into exception and non-exception patterns:

https://github.com/aantron/bisect_ppx/blob/4de17d796a431ca758d006ae1a4259ee39da9cc9/test/instrument/pattern/exception.t#L33-L72

> 2\. If you accept to duplicate sometimes, why not duplicate on every or-pattern to make the problem go away?

Promoting a pattern to the top level and into its own case seems to imply duplicating the guard, which will duplicate side effects or at least evaluation time spent. This is not a problem for partitioning patterns into exception and non-exception patterns, because exceptions and normal evaluation are two completely separate kinds of control flow paths despite being mixed in one `match` expression &mdash; failure to match an exception case due to `false` in a guard does not cause evaluation of a subsequent value case and vice versa.

So, apart from partitioning mixed cases, it seems necessary not to introduce new top-level cases, because it can't be done in general anyway, due to the potential presence of guards. That's why Bisect takes the repeated `match` approach.

I want to link to #43, #56, and #297 here.

> 3\. It looks like you need a heterogeneous approach where `exception ...` always get expanded (with potential duplication of right-hand-sides), potential-GADTs have their scrutinee named and then re-matched, and polymorphic variants need to be carefully left in-place. Ugh.

That's a fairly accurate description of what the code does now, including the "ugh" :) Bisect partitions each case into exception and value patterns, and creates separate cases for them. The case expressions and any gurads on formerly mixed cases become function bodies, and the functions will be called from the unmixed daughter cases. Then,

- For the resulting exception cases, Bisect finds any with or-patterns, inserts `as`-patterns into them under `exception`, and does a secondary `match` inside each case expression to find out which side of the pattern was matched.
- For the resulting value cases, if none have `` `Foo`` or `#foo`, it generates the instrumentation that was added in this PR, with the repeated `match` on `___bisect_matched_value___`. If at least one has a polymorphic variant pattern, it generates the old `as`-instrumentation shown above. The exception instrumentation for exception or-patterns is actually the same, except that the `as` is inserted under `exception` rather than at the top level of the pattern.

    If there are no or-patterns at all in the value cases, Bisect doesn't insert `as` or create a repeated `match`. So the instrumentation is "contracted" and comes out pretty simple, like here:

https://github.com/aantron/bisect_ppx/blob/4de17d796a431ca758d006ae1a4259ee39da9cc9/test/instrument/control/match.t#L4-L16

> 4\. Do we really care about which sides of a toplevel or-pattern where taken, and which were not? If you gave up on this fine-grained information, you could have a much simpler implementation. Do you try to keep track of deep or-patterns? (Eg. `Some (A | B)`)? (The transformations you are doing would be very difficult to perform in-depth, but then those are typed in a less complex way, they cannot contain `exception` patterns, etc., so maybe naming the or-pattern always works.)

Yes, this is important, for example, for parsers written directly as state machines, e.g. Markup.ml. Conveniently, the Markup report is the example for this repo. Consider the typical parser cases instrumented [here](https://aantron.github.io/bisect_ppx/demo/html_parser.ml.html#L1617). Bisect originally did coverage without or-pattern instrumentation, and it was nearly useless for Markup. And yes, these transformations must be (and are) deep. And no, that is not itself difficult :) The code from this PR affects some pretty straightforward "textbook" helpers for doing the various parts of the transformation. Here's an example from a test case:

https://github.com/aantron/bisect_ppx/blob/4de17d796a431ca758d006ae1a4259ee39da9cc9/test/instrument/pattern/unary.t#L27-L48

**Comment by gasche** [comment] 2020-11-03 20:32
This is all a bit horrible but also interesting. It seems to call for some science!

In an ideal world, the following transformation would always be type-preserving:

```ocaml
| p -> e
==>
| p as x ->
  begin match x with p -> () | _ -> assert false end;
  e
```

In the long term we want to "fix" the type-checker to have this property. (In the actual implementation you are not doing `match x with p -> ()`, but something like `match x with $(monitor p)$`, where `monitor p` is a meta-level expansion of p with control-flow monitoring, which it could be interesting to define precise.)

Note also that we have discussed various expansions of pattern-matching constructs, see my somewhat serious [April fool](https://discuss.ocaml.org/t/musings-on-extended-pattern-matching-syntaxes/3600), which may make this transformation unnecessary, instead you would compile `p | q` into something like `(p and (push Left path) with ()) | (q and (push Right path) with ())`.

> Promoting a pattern to the top level and into its own case seems to imply duplicating the guard, which will duplicate side effects or at least evaluation time spent.

I think we can solve this. We have to be careful because guards and or-patterns have a subtle interaction, but I think that

```ocaml
match e with
| C[p | q] when g -> rhs
```

is equivalent to

```ocaml
let guard_fired = ref false
match e with
| C[p] when (guard_fired := true; g) -> rhs
| C[q] when (not !guard_fired && g) -> rhs
```

**Comment by aantron** [comment] 2020-11-03 21:21
I did consider an expansion like that for guards at some point. I recall being dissuaded by other concerns like, again, that rewriting the cases may (will?) affect the types inferred for polymorphic variants, which may lead to unexpected interactions with `rhs`. After coming up with a few such concerns, I decided that the best thing to do for Bisect would be to leave the list of cases alone to the greatest extent possible.

**Comment by mbouaziz** [comment] 2020-11-04 09:37
> @mbouaziz, can you test Bisect_ppx master on your code now? Is the original issue fixed?

It does work now for our usecases. Thanks **a lot** for the fix!

**Comment by gasche** [comment] 2020-11-04 09:59
> I recall being dissuaded by other concerns like, again, that rewriting the cases may (will?) affect the types inferred for polymorphic variants, which may lead to unexpected interactions with rhs.

While there are interaction with polymorphic-variant typing, it may be the case that they cannot break typing for this expansion (I'm an optimistic: I believe it will work).

The main problem with polymorphic variants is that the "open" or "closed" status of the variant is inferred from whether we do a exhaustive or fragile pattern-matching on them; this is the flavor of the examples you have demonstrated above. But with this transformation of `C[p | q]` into `C[p]` or `C[q]`, exhaustiveness (or not) is preserved, so this phenomenon should not come into play.

One difference we do have is that the context `C` may bind its hole subpattern with aliases, and in this case typing can differ in the `rhs`. Consider for example:

```ocaml
# function (`A | `B) as x -> x;;
- : [< `A | `B ] -> [> `A | `B ] = <fun>

# function `A as x -> Ok x | `B as x -> Error x;;
- : [< `A | `B ] -> ([> `A ], [> `B ]) result = <fun>
```

In the first case the inferred type for `x` is ``[> `A | `B]``. With the exploded variant below, the type is either just ``[> `A ]`` or just ``[> `B ]``. The typing context that the right-hand-side sees is different, but note that the post-explosion type is strictly more general than the pre-explosion type: this transformation (unlike transforming an open variant into a closed variant) should preserve typability (and types) for the rest of the program. Again: optimistic, but it may very well work (and arguably it should).

The current implementation you use seems to work okay; it is complex, but maybe just leaving as-is is the reasonable appraoch for now. I have the impression that there would be two way forward:
- Wait for typing of GADTs to "catch up" so that your alias-introduction approach works: one would get a simpler implementation, with splitting of exceptional cases and aliasing otherwise.
- Try the strategy of splitting everything. It's conceptually simpler. I think that it would probably work fine in practice in those corner cases (without requiring type-checker improvements), but it may still lead to a combinatorial explosion for programs that use a lot of nested or-patterns (even if you use functions to share/factorize guards and rhs), so this may introduce other forms of robustness issues.
