### ISSUE TITLE
Unable to generate coverage files with jbuilder instructions.

### ISSUE THREAD

**Issue by cedlemo** [aantron/bisect_ppx#158] opened 2017-08-19 16:44 UTC
I followed the instructions for jbuilder (https://github.com/aantron/bisect_ppx/blob/master/doc/advanced.md#Jbuilder): 

1. I added the following line in the jbuild of my lib : 

    preprocess (pps (bisect_ppx -conditional)))

2. I set the variable `BISECT_ENABLE` to `YES` and ran `jbuilder runtest`

but even if I can see in the output that *bisect_ppx* is used : 

```
...
ocamlopt .ppx/bisect_ppx/ppx.exe
         ppx lib/Builder.pp.ml
         ppx lib/BuilderConstant.pp.ml
         ppx lib/BuilderEnum.pp.ml
         ppx lib/BuilderFunction.pp.ml
         ppx lib/BuilderStruct.pp.ml
...
```

there are no *bisect*.out* files that I can use with `bisect-ppx-report`.

What am I doing wrong ?

**Comment by aantron** [comment] 2017-08-19 16:56
Are the tests actually running? Jbuilder seems not to run tests if nothing they depend on has changed. Could you show your full output?

Even if this is not the cause of your problem, this reminds me to note this in the docs...

**Comment by aantron** [comment] 2017-08-19 16:57
And, are your tests exercising any of the instrumented files?

**Comment by aantron** [comment] 2017-08-19 17:28
@cedlemo, also the files are not generated in the repo root like for other build systems, because Jbuilder changes the directory when tests are run. For example, Lwt has a test binary with a `jbuild` file in `test/core` relative to the repo root. The `bisect*.out` files it generates are found in:

```
_build/default/test/core/
```

You can get all of them using a `find` command:

```
find . -name 'bisect*.out'
```

I need to also add this to the docs.

**Comment by cedlemo** [comment] 2017-08-19 18:03
Firstly here is the jbuild of my lib: 

```
(jbuild_version 1)

(library
 ((name        GObjectIntrospection)
  (public_name ocaml-gobject-introspection)
  (libraries (ctypes ctypes.foreign str))
  (preprocess (pps (bisect_ppx -conditional)))
  (c_flags         (:include c_flags.sexp))
  (c_library_flags (:include c_library_flags.sexp))
  (ocamlopt_flags (-ccopt ("-Wl,-no-as-needed")))
 )
)
(rule
 ((targets (c_flags.sexp
            c_library_flags.sexp))
  (deps    (../config/discover.exe))
  (action  (run ${<} -ocamlc ${OCAMLC}))))
```

secondly here is the output of the command `jbuilder runtest` : 

```
jbuilder runtest
    ocamldep tests/test.depends.ocamldep-output
    ocamldep config/discover.depends.ocamldep-output
      ocamlc lib/GObjectIntrospection.{cmi,cmo,cmt}
    ocamlopt lib/GObjectIntrospection.{cmx,o}
      ocamlc config/discover.{cmi,cmo,cmt}
    ocamlopt config/discover.{cmx,o}
    ocamlopt config/discover.exe
    discover lib/c_flags.sexp,lib/c_library_flags.sexp
==================== Configurator ================
>>>>>>>>>>>>>>>>>>>>> libs : <<<<<<<<<<<<<<<<<<<<<<
(-L/usr/lib/../lib -lffi -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -L/usr/lib/x86_64-linux-gnu -L/usr/lib)
>>>>>>>>>>>>>>>>>>>>> flags : <<<<<<<<<<<<<<<<<<<<<<
(-I/usr/lib/libffi-3.2.1/include -pthread -I/usr/include/gobject-introspection-1.0 -I/usr/lib/libffi-3.2.1/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include -I/usr/include/x86_64-linux-gnu)
==================== Configurator ================
    ocamlopt .ppx/bisect_ppx/ppx.exe
         ppx lib/Builder.pp.ml
         ppx lib/BuilderFunction.pp.ml
         ppx lib/BuilderConstant.pp.ml
         ppx lib/BuilderEnum.pp.ml
         ppx lib/BuilderStruct.pp.ml
         ppx lib/BuilderUnion.pp.ml
         ppx lib/Conversions.pp.ml
         ppx lib/BuilderUtils.pp.ml
         ppx lib/GIBaseInfo.pp.ml
         ppx lib/GICallableInfo.pp.ml
         ppx lib/GIArgInfo.pp.ml
         ppx lib/GIConstantInfo.pp.ml
         ppx lib/GIFieldInfo.pp.ml
         ppx lib/GIFunctionInfo.pp.ml
         ppx lib/GIEnumInfo.pp.ml
         ppx lib/GIPropertyInfo.pp.ml
         ppx lib/GIInterfaceInfo.pp.ml
         ppx lib/GIRegisteredTypeInfo.pp.ml
         ppx lib/GISignalInfo.pp.ml
         ppx lib/GIStructInfo.pp.ml
         ppx lib/GITypeInfo.pp.ml
         ppx lib/GITypes.pp.ml
         ppx lib/GIUnionInfo.pp.ml
         ppx lib/GIVFuncInfo.pp.ml
         ppx lib/GIObjectInfo.pp.ml
         ppx lib/GIValueInfo.pp.ml
         ppx lib/Loader.pp.ml
         ppx lib/Repository.pp.ml
         ppx lib/BuilderConstant.pp.mli
         ppx lib/BuilderStruct.pp.mli
         ppx lib/Builder.pp.mli
         ppx lib/BuilderEnum.pp.mli
         ppx lib/BuilderFunction.pp.mli
         ppx lib/BuilderUtils.pp.mli
         ppx lib/GIArgInfo.pp.mli
         ppx lib/GIBaseInfo.pp.mli
         ppx lib/GICallableInfo.pp.mli
         ppx lib/GIConstantInfo.pp.mli
         ppx lib/BuilderUnion.pp.mli
         ppx lib/GIEnumInfo.pp.mli
         ppx lib/GIFunctionInfo.pp.mli
         ppx lib/GIFieldInfo.pp.mli
         ppx lib/GIRegisteredTypeInfo.pp.mli
         ppx lib/GIPropertyInfo.pp.mli
         ppx lib/GIInterfaceInfo.pp.mli
         ppx lib/GIObjectInfo.pp.mli
         ppx lib/GISignalInfo.pp.mli
         ppx lib/GITypeInfo.pp.mli
         ppx lib/GITypes.pp.mli
         ppx lib/GIStructInfo.pp.mli
         ppx lib/GIUnionInfo.pp.mli
         ppx lib/GIVFuncInfo.pp.mli
         ppx lib/GIValueInfo.pp.mli
         ppx lib/Loader.pp.mli
         ppx lib/Repository.pp.mli
    ocamldep lib/GObjectIntrospection.depends.ocamldep-output
    ocamldep lib/GObjectIntrospection.dependsi.ocamldep-output
      ocamlc lib/GObjectIntrospection__GIBaseInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__Conversions.{cmi,cmo,cmt}
      ocamlc lib/GObjectIntrospection__GIValueInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__Builder.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GITypes.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__Repository.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__Loader.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GITypeInfo.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__Conversions.{cmx,o}
    ocamlopt lib/GObjectIntrospection__GIBaseInfo.{cmx,o}
      ocamlc lib/GObjectIntrospection__GIArgInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GIFieldInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GIRegisteredTypeInfo.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__GITypes.{cmx,o}
      ocamlc lib/GObjectIntrospection__BuilderUtils.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GIConstantInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GIPropertyInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GICallableInfo.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__GIValueInfo.{cmx,o}
      ocamlc lib/GObjectIntrospection__GISignalInfo.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__Repository.{cmx,o}
      ocamlc lib/GObjectIntrospection__BuilderConstant.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GIVFuncInfo.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__GITypeInfo.{cmx,o}
      ocamlc lib/GObjectIntrospection__GIFunctionInfo.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__GIFieldInfo.{cmx,o}
    ocamlopt lib/GObjectIntrospection__GIRegisteredTypeInfo.{cmx,o}
    ocamlopt lib/GObjectIntrospection__GIArgInfo.{cmx,o}
      ocamlc lib/GObjectIntrospection__BuilderFunction.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__GIConstantInfo.{cmx,o}
      ocamlc lib/GObjectIntrospection__GIStructInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__GIEnumInfo.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__BuilderUtils.{cmx,o}
      ocamlc lib/GObjectIntrospection__GIUnionInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__BuilderStruct.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__GIPropertyInfo.{cmx,o}
      ocamlc lib/GObjectIntrospection__BuilderEnum.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__BuilderConstant.{cmx,o}
    ocamlopt lib/GObjectIntrospection__GICallableInfo.{cmx,o}
      ocamlc lib/GObjectIntrospection__GIInterfaceInfo.{cmi,cmti}
      ocamlc lib/GObjectIntrospection__BuilderUnion.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__GISignalInfo.{cmx,o}
      ocamlc lib/GObjectIntrospection__GIObjectInfo.{cmi,cmti}
    ocamlopt lib/GObjectIntrospection__GIVFuncInfo.{cmx,o}
      ocamlc tests/TestUtils.{cmi,cmo,cmt}
    ocamlopt lib/GObjectIntrospection__GIFunctionInfo.{cmx,o}
      ocamlc tests/TestBuilderFunction.{cmi,cmo,cmt}
      ocamlc tests/TestBuilderStruct.{cmi,cmo,cmt}
      ocamlc tests/TestBuilderEnum.{cmi,cmo,cmt}
      ocamlc tests/TestBuilderUnion.{cmi,cmo,cmt}
File "tests/TestBuilderUnion.ml", line 68, characters 6-12:
Warning 26: unused variable writer.
File "tests/TestBuilderUnion.ml", line 69, characters 6-17:
Warning 26: unused variable mli_content.
File "tests/TestBuilderUnion.ml", line 71, characters 6-16:
Warning 26: unused variable ml_content.
      ocamlc tests/TestBuilderConstant.{cmi,cmo,cmt}
      ocamlc tests/TestBuilderUtils.{cmi,cmo,cmt}
      ocamlc tests/TestGIArgInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGICallableInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIBaseInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIConstantInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIEnumInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIFieldInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIInterfaceInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIFunctionInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIPropertyInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIRepository.{cmi,cmo,cmt}
      ocamlc tests/TestGIObjectInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGISignalInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIRegisteredTypeInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIStructInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIVFuncInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGITypeInfo.{cmi,cmo,cmt}
      ocamlc tests/TestGIUnionInfo.{cmi,cmo,cmt}
      ocamlc tests/TestLoader.{cmi,cmo,cmt}
    ocamlopt lib/GObjectIntrospection__GIEnumInfo.{cmx,o}
    ocamlopt lib/GObjectIntrospection__GIStructInfo.{cmx,o}
    ocamlopt lib/GObjectIntrospection__BuilderFunction.{cmx,o}
      ocamlc tests/test.{cmi,cmo,cmt}
    ocamlopt lib/GObjectIntrospection__BuilderStruct.{cmx,o}
    ocamlopt lib/GObjectIntrospection__BuilderEnum.{cmx,o}
    ocamlopt lib/GObjectIntrospection__GIUnionInfo.{cmx,o}
    ocamlopt lib/GObjectIntrospection__GIInterfaceInfo.{cmx,o}
    ocamlopt lib/GObjectIntrospection__BuilderUnion.{cmx,o}
    ocamlopt lib/GObjectIntrospection__Builder.{cmx,o}
    ocamlopt lib/GObjectIntrospection__GIObjectInfo.{cmx,o}
    ocamlopt lib/GObjectIntrospection__Loader.{cmx,o}
    ocamlopt tests/TestUtils.{cmx,o}
    ocamlopt tests/TestBuilderFunction.{cmx,o}
    ocamlopt tests/TestBuilderConstant.{cmx,o}
    ocamlopt tests/TestBuilderEnum.{cmx,o}
    ocamlopt tests/TestBuilderStruct.{cmx,o}
    ocamlopt tests/TestBuilderUtils.{cmx,o}
    ocamlopt tests/TestBuilderUnion.{cmx,o}
File "tests/TestBuilderUnion.ml", line 68, characters 6-12:
Warning 26: unused variable writer.
File "tests/TestBuilderUnion.ml", line 69, characters 6-17:
Warning 26: unused variable mli_content.
File "tests/TestBuilderUnion.ml", line 71, characters 6-16:
Warning 26: unused variable ml_content.
    ocamlopt tests/TestGICallableInfo.{cmx,o}
    ocamlopt tests/TestGIBaseInfo.{cmx,o}
    ocamlopt tests/TestGIArgInfo.{cmx,o}
    ocamlopt tests/TestGIConstantInfo.{cmx,o}
    ocamlopt tests/TestGIEnumInfo.{cmx,o}
    ocamlopt tests/TestGIFieldInfo.{cmx,o}
    ocamlopt lib/GObjectIntrospection.{a,cmxa}
    ocamlopt tests/TestGIFunctionInfo.{cmx,o}
    ocamlopt tests/TestGIInterfaceInfo.{cmx,o}
    ocamlopt tests/TestGIPropertyInfo.{cmx,o}
    ocamlopt tests/TestGIRegisteredTypeInfo.{cmx,o}
    ocamlopt tests/TestGIRepository.{cmx,o}
    ocamlopt tests/TestGIObjectInfo.{cmx,o}
    ocamlopt tests/TestGISignalInfo.{cmx,o}
    ocamlopt tests/TestGIStructInfo.{cmx,o}
    ocamlopt tests/TestGITypeInfo.{cmx,o}
    ocamlopt tests/TestGIVFuncInfo.{cmx,o}
    ocamlopt tests/TestGIUnionInfo.{cmx,o}
    ocamlopt tests/TestLoader.{cmx,o}
    ocamlopt tests/test.{cmx,o}
    ocamlopt tests/test.exe
        test alias tests/runtest
........................................................................................................................................................................................................
Ran: 200 tests in: 0.14 seconds.
OK
```

And yes I already tried the `find` command before creating a new issue :).

**Comment by aantron** [comment] 2017-08-19 18:10
Looking at it. In the meantime, I applied Bisect_ppx using `-coverage` to Lwt; it's working. You may want to glance at this diff: https://github.com/ocsigen/lwt/pull/465/files. It touches, I think, all of the lines needed to make a report.

**Comment by aantron** [comment] 2017-08-19 18:20
Can you show how you set `BISECT_ENABLE` to `YES`?

(Update: I tried running something similar based on the repo in GitHub, but the code seems Linux-specific at the moment, so I'm moving to a Linux machine...)

```
    ocamlopt lib/GObjectIntrospection.cmxs (exit 2)
(cd _build/default && /Users/antron/.opam/4.04.2-lwt/bin/ocamlopt.opt -w -40 -ccopt -Wl,-no-as-needed -shared -linkall -I lib -o lib/GObjectIntrospection.cmxs lib/GObjectIntrospection.cmxa)
ld: warning: directory not found for option '-L/usr/lib/x86_64-linux-gnu'
ld: unknown option: -no-as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
```

**Comment by aantron** [comment] 2017-08-19 18:42
I was able to get `.out` files. I suspect `BISECT_ENABLE` isn't actually set to `YES` :)

```
$ BISECT_ENABLE=YES jbuilder runtest
...
$ find . -name 'bisect*.out'
./_build/default/tests/bisect0001.out
./_build/default/tests/bisect0002.out
```

The changes to the code from `master` were:

```diff
diff --git a/lib/jbuild b/lib/jbuild
index 0769487..b349513 100644
--- a/lib/jbuild
+++ b/lib/jbuild
@@ -4,6 +4,7 @@
  ((name        GObjectIntrospection)
   (public_name ocaml-gobject-introspection)
   (libraries (ctypes ctypes.foreign str))
+  (preprocess (pps (bisect_ppx -conditional)))
   (c_flags         (:include c_flags.sexp))
   (c_library_flags (:include c_library_flags.sexp))
   (ocamlopt_flags (-ccopt ("-Wl,-no-as-needed")))
```

If this resolves the issue, I'd like to still leave it open, to remind myself to fix those doc oversights :) Thanks for prompting more thinking about it :)

**Comment by cedlemo** [comment] 2017-08-19 19:22
@aantron,

I am very sorry to have wasted your time. It appears that like you suspected on my system, the `BISECT_ENABLE` was not set, I use the fish shell  and I used `set BISECT_ENABLE YES; jbuilder runtest` instead of `set -x BISECT_ENABLE YES; jbuilder runtest`.

Furthermore when I tested with a simple Makefile : 

```
.PHONY : coverage
 coverage :
	BISECT_ENABLE=YES jbuilder runtest
	bisect-ppx-report -html _coverage/ bisect0001.out
```

it did not work but with the following, everything was OK with `make coverage` : 

```
.PHONY : coverage
 coverage :
	BISECT_ENABLE=YES jbuilder runtest
	bisect-ppx-report -html _coverage/ ./_build/default/tests/bisect0001.out
```

Thanks for your help.

**Comment by aantron** [comment] 2017-08-19 19:30
No worries, I didn't think it was a waste of time. It prompted me to also try this in a "real" project of my own (as opposed to Bisect_ppx's internal little usage test programs), and to think about it more. I still have more doc improvements to make as a result :)

Indeed, you'll see that the docs [now actually suggest](https://github.com/aantron/bisect_ppx/blob/master/doc/advanced.md#Jbuilder) to run a `find` command :) But they also need to suggest passing `-I _build/default/` to the reporter, and we should add a Jbuilder-friendly command line example to the reporter's own help output. So don't click on that link for another 10 minutes :p

Regarding your `bisect-ppx-report` invocations, I suggest that you always use `whatever/directory/bisect*.out`. This is because if your testing is concurrent (and with many testing frameworks, it is by default), you will get `bisect0001.out` and `bisect0002.out`, etc. You want to get the coverage data from all of them, not just the first process that the testing framework forked.

**Closed** 2017-08-19 19:37 UTC
