### ISSUE TITLE
ppxlib >= 0.28 compatibility

### ISSUE THREAD

**Issue by sim642** [aantron/bisect_ppx#419] opened 2023-06-09 08:46 UTC
The current latest version of bisect_ppx is 2.8.2 and that has the constraint ppxlib < 0.28.
Ppxlib 0.28 and 0.29 have been out for a while, so it would be great to be compatible.

**Comment by aantron** [comment] 2023-06-25 10:05
This was fixed by #413 and was a duplicate of #410. Thank you!

**Closed by aantron** 2023-06-25 10:05 UTC

**Comment by johnhaley81** [comment] 2023-07-16 20:10
@aantron is it possible to get this published on opam please?
